<?xml version="1.0"?>
<package format="3">
  <name>gl5_detection</name>
  <version>0.1.0</version>
  <description>GL5 region editing, obstacle detection and tracking</description>
  <maintainer email="dhkim@example.com">dhkim</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>interactive_markers</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>gl5_localization</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rosidl_runtime_py</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
