find_path(SOSLAB_INCLUDE_DIR Lidar.h PATHS "${SOSLAB_SDK_ROOT}/include" NO_DEFAULT_PATH REQUIRED)
find_library(SOSLAB_LIBRARY NAMES Lidar_x64_release Lidar_x86_release
  PATHS "${SOSLAB_SDK_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
add_library(soslab_sdk SHARED IMPORTED)
set_target_properties(soslab_sdk PROPERTIES
  IMPORTED_LOCATION "${SOSLAB_LIBRARY}"
  INTERFACE_INCLUDE_DIRECTORIES "${SOSLAB_INCLUDE_DIR};${SOSLAB_INCLUDE_DIR}/nlohmann_json")
